---
- name: Set Up Environment
  hosts: localhost
  become: no
  vars:
    os_family_linux:
      - "Debian"
      - "RedHat"
      - "Suse"
    PACKAGES_TO_INSTALL:
      - fzf
      - bat
      - zoxide
      - ripgrep
      - neovim
      - uv
      - kubectl
      - kubecm
      - helm
      - powerlevel10k

  tasks:
  # Common Packages
  - name: Install Common Packages
    community.general.homebrew:
      name: "{{ PACKAGES_TO_INSTALL }}"
      state: present
        
  # Platform Specific Packages
  - name: Install Podman [Linux]
    when: ansible_facts['os_family'] in os_family_linux
    community.general.homebrew:
      name: podman
      state: present

  - name: Install Orbstack [Mac]
    when: ansible_facts['os_family'] == "Darwin"
    community.general.homebrew:
      name: orbstack
      state: present
      state: present

  # Utility Setup
  - name: Set up fzf shell integration
    ansible.builtin.lineinfile:
      create: true
      path: $HOME/.zshrc
      regexp: 'source\s+<\s*\(\s*fzf\s+--zsh\s*\)\s*'
      line: "source <(fzf --zsh)"

  - name: download fzf-git integrations
    ansible.builtin.git:
      repo: https://github.com/junegunn/fzf-git.sh
      dest: $HOME/.config/fzf-git
        
  - name: add fzf-git to zshrc
    ansible.builtin.lineinfile:
      create: true
      path: $HOME/.zshrc
      regexp: 'source\s+\$HOME/.config/fzf-git/fzf-git.sh'
      line: 'source $HOME/.config/fzf-git/fzf-git.sh'

  - name: Setup zoxide
    ansible.builtin.lineinfile:
      create: true
      path: $HOME/.zshrc
      regexp: 'eval\s+\(\s*zoxide\s+init\s+zsh\s*\)'
      line: 'eval "$(zoxide init zsh)"'


  # Shell Visual Customization
  - name: Set Up Powerlevel10k
    ansible.builtin.lineinfile:
     create: true
     path: $HOME/.zshrc
     regexp: 'source\s+.*powerlevel10k.zsh-theme'
     line: "source {{ ansible_env.HOMEBREW_PREFIX }}/share/powerlevel10k/powerlevel10k.zsh-theme"

    
    


# To Install:
#X fzf
# fzf git integrations
#X kubectl
#X uv
# helm
#X bat
#X jq
#X nvim
#X zoxide
#X rg
#X podman if linux
#X orbstack if mac
# p10k

